const symbol = {
  _class: 'symbolMaster',
  frame: {
    _class: 'rect',
    constrainProportions: false,
    height: 22,
    width: 40,
    x: 162.265625,
    y: 50,
  },
  allowsOverrides: true,
  backgroundColor: { _class: 'color', red: 1, green: 1, blue: 1, alpha: 1 },
  booleanOperation: -1,
  changeIdentifier: 0,
  do_objectID: '6333B9D8-49CC-431E-A30C-07D9C85A136B',
  symbolID: '40940151-D7F0-430A-A686-ECB36490A185',
  exportOptions: {
    _class: 'exportOptions',
    includedLayerIds: [],
    layerOptions: 0,
    shouldTrim: false,
    exportFormats: [],
  },
  hasClickThrough: true,
  includeInCloudUpload: true,
  hasBackgroundColor: false,
  includeBackgroundColorInExport: true,
  resizesContent: false,
  includeBackgroundColorInInstance: false,
  nameIsFixed: false,
  horizontalRulerData: { _class: 'rulerData', base: 0, guides: [] },
  verticalRulerData: { _class: 'rulerData', base: 0, guides: [] },
  resizingConstraint: 1,
  resizingType: 1,
  groupLayout: { _class: 'MSImmutableFreeformGroupLayout' },
  isFixedToViewport: false,
  sharedStyleID: '',
  isFlippedHorizontal: false,
  isFlippedVertical: false,
  isLocked: false,
  isFlowHome: false,
  name: '1.Tag 标签/1.Default默认/1.Off关',
  rotation: 0,
  layerListExpandedType: 0,
  overrideProperties: [
    {
      _class: 'MSImmutableOverrideProperty',
      canOverride: true,
      overrideName: 'BA41E2BE-CD18-451A-AF1C-DDC669EF2F76_stringValue',
    },
  ],
  layers: [
    {
      _class: 'group',
      do_objectID: 'DFC1E427-1632-44AB-8F69-5D7E00F9E1ED',
      booleanOperation: -1,
      isFixedToViewport: false,
      isFlippedHorizontal: false,
      isFlippedVertical: false,
      isVisible: true,
      isLocked: false,
      layerListExpandedType: 0,
      name: '编组',
      nameIsFixed: false,
      resizingConstraint: 63,
      resizingType: 0,
      rotation: 0,
      shouldBreakMaskChain: false,
      exportOptions: {
        _class: 'exportOptions',
        includedLayerIds: [],
        layerOptions: 0,
        shouldTrim: false,
        exportFormats: [],
      },
      frame: {
        _class: 'rect',
        constrainProportions: false,
        height: 22,
        width: 40,
        x: 0,
        y: 0,
      },
      clippingMaskMode: 0,
      hasClippingMask: false,
      style: {
        _class: 'style',
        do_objectID: 'D29D1015-4F45-4A6B-B867-80FBED5CD839',
        endMarkerType: 0,
        miterLimit: 10,
        startMarkerType: 0,
        windingRule: 1,
        borderOptions: {
          _class: 'borderOptions',
          isEnabled: true,
          dashPattern: [],
          lineCapStyle: 0,
          lineJoinStyle: 0,
        },
        colorControls: {
          _class: 'colorControls',
          isEnabled: false,
          brightness: 0,
          contrast: 1,
          hue: 0,
          saturation: 1,
        },
        fills: [],
        borders: [],
        shadows: [],
        innerShadows: [],
        contextSettings: {
          _class: 'graphicsContextSettings',
          blendMode: 0,
          opacity: 1,
        },
      },
      hasClickThrough: false,
      groupLayout: { _class: 'MSImmutableFreeformGroupLayout' },
      layers: [
        {
          _class: 'rectangle',
          name: 'BG',
          resizingConstraint: 3,
          frame: {
            _class: 'rect',
            constrainProportions: false,
            height: 22,
            width: 40,
            x: 0,
            y: 0,
          },
          do_objectID: '544BA6B9-7A0E-45CD-9825-CBF84A44E03C',
          hasConvertedToNewRoundCorners: true,
          needsConvertionToNewRoundCorners: false,
          fixedRadius: 0,
          style: {
            _class: 'style',
            do_objectID: '743C9417-C30D-4FC3-9AA9-DA702C02E231',
            endMarkerType: 0,
            miterLimit: 10,
            startMarkerType: 0,
            windingRule: 1,
            borderOptions: {
              _class: 'borderOptions',
              isEnabled: true,
              dashPattern: [],
              lineCapStyle: 0,
              lineJoinStyle: 0,
            },
            colorControls: {
              _class: 'colorControls',
              isEnabled: false,
              brightness: 0,
              contrast: 1,
              hue: 0,
              saturation: 1,
            },
            fills: [
              {
                _class: 'fill',
                isEnabled: true,
                fillType: 0,
                color: {
                  _class: 'color',
                  red: 0.9803921568627451,
                  green: 0.9803921568627451,
                  blue: 0.9803921568627451,
                  alpha: 1,
                },
                contextSettings: {
                  _class: 'graphicsContextSettings',
                  blendMode: 0,
                  opacity: 1,
                },
                noiseIndex: 0,
                noiseIntensity: 0,
                patternFillType: 1,
                patternTileScale: 1,
              },
            ],
            borders: [
              {
                _class: 'border',
                isEnabled: true,
                fillType: 0,
                color: {
                  _class: 'color',
                  red: 0.8509803921568627,
                  green: 0.8509803921568627,
                  blue: 0.8509803921568627,
                  alpha: 1,
                },
                contextSettings: {
                  _class: 'graphicsContextSettings',
                  blendMode: 0,
                  opacity: 1,
                },
                position: 1,
                thickness: 1,
              },
            ],
            shadows: [],
            innerShadows: [],
            contextSettings: {
              _class: 'graphicsContextSettings',
              blendMode: 0,
              opacity: 1,
            },
          },
          edited: false,
          pointRadiusBehaviour: 1,
          points: [
            {
              _class: 'curvePoint',
              cornerRadius: 2,
              curveFrom: '{0, 0}',
              curveMode: 1,
              curveTo: '{0, 0}',
              hasCurveFrom: false,
              hasCurveTo: false,
              point: '{0, 0}',
            },
            {
              _class: 'curvePoint',
              cornerRadius: 2,
              curveFrom: '{1, 0}',
              curveMode: 1,
              curveTo: '{1, 0}',
              hasCurveFrom: false,
              hasCurveTo: false,
              point: '{1, 0}',
            },
            {
              _class: 'curvePoint',
              cornerRadius: 2,
              curveFrom: '{1, 1}',
              curveMode: 1,
              curveTo: '{1, 1}',
              hasCurveFrom: false,
              hasCurveTo: false,
              point: '{1, 1}',
            },
            {
              _class: 'curvePoint',
              cornerRadius: 2,
              curveFrom: '{0, 1}',
              curveMode: 1,
              curveTo: '{0, 1}',
              hasCurveFrom: false,
              hasCurveTo: false,
              point: '{0, 1}',
            },
          ],
          isClosed: true,
          booleanOperation: -1,
          exportOptions: {
            _class: 'exportOptions',
            includedLayerIds: [],
            layerOptions: 0,
            shouldTrim: false,
            exportFormats: [],
          },
          isVisible: true,
          isFixedToViewport: false,
          isFlippedHorizontal: false,
          isFlippedVertical: false,
          layerListExpandedType: 0,
          nameIsFixed: false,
          resizingType: 0,
          rotation: 0,
          shouldBreakMaskChain: false,
          clippingMaskMode: 0,
          isLocked: false,
        },
        {
          _class: 'text',
          do_objectID: 'BA41E2BE-CD18-451A-AF1C-DDC669EF2F76',
          booleanOperation: -1,
          isFixedToViewport: false,
          isFlippedHorizontal: false,
          isFlippedVertical: false,
          isLocked: false,
          isVisible: true,
          name: '文本',
          nameIsFixed: false,
          layerListExpandedType: 0,
          resizingConstraint: 63,
          resizingType: 0,
          rotation: 0,
          shouldBreakMaskChain: false,
          exportOptions: {
            _class: 'exportOptions',
            includedLayerIds: [],
            layerOptions: 0,
            shouldTrim: false,
            exportFormats: [],
          },
          frame: {
            _class: 'rect',
            constrainProportions: false,
            height: 20,
            width: 24,
            x: 7,
            y: 0,
          },
          clippingMaskMode: 0,
          hasClippingMask: false,
          style: {
            _class: 'style',
            do_objectID: 'BC84A1E1-F2DB-4EF6-A9FF-B90653185F8D',
            endMarkerType: 0,
            miterLimit: 10,
            startMarkerType: 0,
            windingRule: 1,
            borderOptions: {
              _class: 'borderOptions',
              isEnabled: true,
              dashPattern: [],
              lineCapStyle: 0,
              lineJoinStyle: 0,
            },
            colorControls: {
              _class: 'colorControls',
              isEnabled: false,
              brightness: 0,
              contrast: 1,
              hue: 0,
              saturation: 1,
            },
            fills: [],
            borders: [],
            shadows: [],
            innerShadows: [],
            contextSettings: {
              _class: 'graphicsContextSettings',
              blendMode: 0,
              opacity: 1,
            },
          },
          attributedString: {
            _class: 'attributedString',
            string: '内容',
            attributes: [
              {
                _class: 'stringAttribute',
                location: 0,
                length: 2,
                attributes: {
                  underlineStyle: 0,
                  MSAttributedStringTextTransformAttribute: 0,
                  paragraphStyle: {
                    _class: 'paragraphStyle',
                    maximumLineHeight: 20,
                    minimumLineHeight: 20,
                  },
                  kerning: 0,
                  strikethroughStyle: 0,
                  MSAttributedStringFontAttribute: {
                    _class: 'fontDescriptor',
                    attributes: { name: 'PingFangSC-Regular', size: 12 },
                  },
                  MSAttributedStringColorAttribute: {
                    _class: 'color',
                    red: 0,
                    green: 0,
                    blue: 0,
                    alpha: 0.65,
                  },
                },
              },
            ],
          },
          automaticallyDrawOnUnderlyingPath: false,
          dontSynchroniseWithSymbol: false,
          lineSpacingBehaviour: 2,
          textBehaviour: 0,
          glyphBounds: '',
        },
      ],
      userInfo: null,
    },
  ],
  isVisible: true,
};

describe('nodeToSketchSymbol', function() {
  it('should work fine', function() {});
});
