// import { Tag } from 'antd';

import { nodeToSketchGroup } from '../../../../lib';

const tag = {
  _class: 'group',
  do_objectID: 'AE685E87-B296-4E67-AAA3-FCA61BE89E31',
  booleanOperation: -1,
  isFixedToViewport: false,
  isFlippedHorizontal: false,
  isFlippedVertical: false,
  isVisible: true,
  isLocked: false,
  layerListExpandedType: 0,
  name: '编组',
  nameIsFixed: false,
  resizingConstraint: 63,
  resizingType: 0,
  rotation: 0,
  shouldBreakMaskChain: false,
  exportOptions: {
    _class: 'exportOptions',
    includedLayerIds: [],
    layerOptions: 0,
    shouldTrim: false,
    exportFormats: [],
  },
  frame: {
    _class: 'rect',
    constrainProportions: false,
    height: 22,
    width: 40,
    x: 162.265625,
    y: 50,
  },
  clippingMaskMode: 0,
  hasClippingMask: false,
  style: {
    _class: 'style',
    do_objectID: '457A2E84-AC0F-42C0-9A92-F629A162C292',
    endMarkerType: 0,
    miterLimit: 10,
    startMarkerType: 0,
    windingRule: 1,
    borderOptions: {
      _class: 'borderOptions',
      isEnabled: true,
      dashPattern: [],
      lineCapStyle: 0,
      lineJoinStyle: 0,
    },
    colorControls: {
      _class: 'colorControls',
      isEnabled: false,
      brightness: 0,
      contrast: 1,
      hue: 0,
      saturation: 1,
    },
    fills: [],
    borders: [],
    shadows: [],
    innerShadows: [],
    contextSettings: {
      _class: 'graphicsContextSettings',
      blendMode: 0,
      opacity: 1,
    },
  },
  hasClickThrough: false,
  groupLayout: { _class: 'MSImmutableFreeformGroupLayout' },
  layers: [
    {
      _class: 'rectangle',
      name: 'ant-tag test',
      resizingConstraint: 3,
      frame: {
        _class: 'rect',
        constrainProportions: false,
        height: 22,
        width: 40,
        x: 0,
        y: 0,
      },
      do_objectID: '6970923D-68E8-43FE-A7E4-E496E3357955',
      hasConvertedToNewRoundCorners: true,
      needsConvertionToNewRoundCorners: false,
      fixedRadius: 0,
      style: {
        _class: 'style',
        do_objectID: '4980B0E5-E573-4EE2-A796-E67B9D7793FC',
        endMarkerType: 0,
        miterLimit: 10,
        startMarkerType: 0,
        windingRule: 1,
        borderOptions: {
          _class: 'borderOptions',
          isEnabled: true,
          dashPattern: [],
          lineCapStyle: 0,
          lineJoinStyle: 0,
        },
        colorControls: {
          _class: 'colorControls',
          isEnabled: false,
          brightness: 0,
          contrast: 1,
          hue: 0,
          saturation: 1,
        },
        fills: [
          {
            _class: 'fill',
            isEnabled: true,
            fillType: 0,
            color: {
              _class: 'color',
              red: 0.9803921568627451,
              green: 0.9803921568627451,
              blue: 0.9803921568627451,
              alpha: 1,
            },
            contextSettings: {
              _class: 'graphicsContextSettings',
              blendMode: 0,
              opacity: 1,
            },
            noiseIndex: 0,
            noiseIntensity: 0,
            patternFillType: 1,
            patternTileScale: 1,
          },
        ],
        borders: [
          {
            _class: 'border',
            isEnabled: true,
            fillType: 0,
            color: {
              _class: 'color',
              red: 0.8509803921568627,
              green: 0.8509803921568627,
              blue: 0.8509803921568627,
              alpha: 1,
            },
            contextSettings: {
              _class: 'graphicsContextSettings',
              blendMode: 0,
              opacity: 1,
            },
            position: 1,
            thickness: 1,
          },
        ],
        shadows: [],
        innerShadows: [],
        contextSettings: {
          _class: 'graphicsContextSettings',
          blendMode: 0,
          opacity: 1,
        },
      },
      edited: false,
      pointRadiusBehaviour: 1,
      points: [
        {
          _class: 'curvePoint',
          cornerRadius: 2,
          curveFrom: '{0, 0}',
          curveMode: 1,
          curveTo: '{0, 0}',
          hasCurveFrom: false,
          hasCurveTo: false,
          point: '{0, 0}',
        },
        {
          _class: 'curvePoint',
          cornerRadius: 2,
          curveFrom: '{1, 0}',
          curveMode: 1,
          curveTo: '{1, 0}',
          hasCurveFrom: false,
          hasCurveTo: false,
          point: '{1, 0}',
        },
        {
          _class: 'curvePoint',
          cornerRadius: 2,
          curveFrom: '{1, 1}',
          curveMode: 1,
          curveTo: '{1, 1}',
          hasCurveFrom: false,
          hasCurveTo: false,
          point: '{1, 1}',
        },
        {
          _class: 'curvePoint',
          cornerRadius: 2,
          curveFrom: '{0, 1}',
          curveMode: 1,
          curveTo: '{0, 1}',
          hasCurveFrom: false,
          hasCurveTo: false,
          point: '{0, 1}',
        },
      ],
      isClosed: true,
      booleanOperation: -1,
      exportOptions: {
        _class: 'exportOptions',
        includedLayerIds: [],
        layerOptions: 0,
        shouldTrim: false,
        exportFormats: [],
      },
      isVisible: true,
      isFixedToViewport: false,
      isFlippedHorizontal: false,
      isFlippedVertical: false,
      layerListExpandedType: 0,
      nameIsFixed: false,
      resizingType: 0,
      rotation: 0,
      shouldBreakMaskChain: false,
      clippingMaskMode: 0,
      isLocked: false,
    },
    {
      _class: 'text',
      do_objectID: '927D56B1-7896-4272-85CD-40F848F15722',
      booleanOperation: -1,
      isFixedToViewport: false,
      isFlippedHorizontal: false,
      isFlippedVertical: false,
      isLocked: false,
      isVisible: true,
      name: '内容',
      nameIsFixed: false,
      layerListExpandedType: 0,
      resizingConstraint: 63,
      resizingType: 0,
      rotation: 0,
      shouldBreakMaskChain: false,
      exportOptions: {
        _class: 'exportOptions',
        includedLayerIds: [],
        layerOptions: 0,
        shouldTrim: false,
        exportFormats: [],
      },
      frame: {
        _class: 'rect',
        constrainProportions: false,
        height: 20,
        width: 24,
        x: 7,
        y: 0,
      },
      clippingMaskMode: 0,
      hasClippingMask: false,
      style: {
        _class: 'style',
        do_objectID: 'FD1FF1F2-9D32-447D-9D88-CEAAE468BD72',
        endMarkerType: 0,
        miterLimit: 10,
        startMarkerType: 0,
        windingRule: 1,
        borderOptions: {
          _class: 'borderOptions',
          isEnabled: true,
          dashPattern: [],
          lineCapStyle: 0,
          lineJoinStyle: 0,
        },
        colorControls: {
          _class: 'colorControls',
          isEnabled: false,
          brightness: 0,
          contrast: 1,
          hue: 0,
          saturation: 1,
        },
        fills: [],
        borders: [],
        shadows: [],
        innerShadows: [],
        contextSettings: {
          _class: 'graphicsContextSettings',
          blendMode: 0,
          opacity: 1,
        },
      },
      attributedString: {
        _class: 'attributedString',
        string: '内容',
        attributes: [
          {
            _class: 'stringAttribute',
            location: 0,
            length: 2,
            attributes: {
              underlineStyle: 0,
              MSAttributedStringTextTransformAttribute: 0,
              paragraphStyle: {
                _class: 'paragraphStyle',
                maximumLineHeight: 20,
                minimumLineHeight: 20,
              },
              kerning: 0,
              strikethroughStyle: 0,
              MSAttributedStringFontAttribute: {
                _class: 'fontDescriptor',
                attributes: { name: 'PingFangSC-Regular', size: 12 },
              },
              MSAttributedStringColorAttribute: {
                _class: 'color',
                red: 0,
                green: 0,
                blue: 0,
                alpha: 0.65,
              },
            },
          },
        ],
      },
      automaticallyDrawOnUnderlyingPath: false,
      dontSynchroniseWithSymbol: false,
      lineSpacingBehaviour: 2,
      textBehaviour: 0,
      glyphBounds: '',
    },
  ],
  userInfo: null,
};

describe('tag', () => {
  beforeAll(() => {
    document.body.innerHTML = `  
    <tag id="tag">内容</tag>
    `;
  });
  afterAll(() => {
    document.body.innerHTML = '';
  });
  it('should ', () => {
    const data = nodeToSketchGroup(document.getElementById('tag'));

    expect(data).toStrictEqual(tag);
  });
});
